---
- hosts: vpc
  vars_prompt:
    - name: "cidr_block"
      prompt: "10.0.0.0/16"
      private: no
    - name: "vpc_name"
      prompt: "ohio_vpc"
      private: no
    - name: "region"
      prompt: "ohio"
      private: no
    - name: "tag_env"
      prompt: "tag_env"
      private: no
  tasks:
    - set_fact:
        cidr_block: "{{cidr_block}}"
        vpc_name: "{{vpc_name}}"
        region: "{{region}}"
        tag_env: "{{tag_env}}"
  roles:
    - ../roles/vpc
  
